#!/usr/bin/with-contenv sh

if [ ! -z $WEB_ROOT ]; then
    sed -i 's!\(set $root\).*$!\1 '"\'$WEB_ROOT\'"';!' /etc/nginx/nginx.conf
fi

if [ -z $TUNNEL_FIXED ]; then
    tunnel_token=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13)
    echo "${tunnel_token}" > /.tunnel-token
    echo "tunnel url is \`/tunnel-${tunnel_token}\`"
    sed -i 's!\(tunnel\).*{$!\1'"-$tunnel_token"' {!' /etc/nginx/nginx.conf
fi

sed -i 's/$ngx_resolver/'"${NGX_RESOLVER:-8.8.8.8}"'/' /etc/nginx/nginx.conf

echo >&2 "starting nginx"

exec /opt/nginx/sbin/nginx 2>&1
