#!/usr/bin/with-contenv bash

if [ -f /setup-php ]; then
  bash /setup-php
  mv /setup-php /setup-php.$(date -Is)
fi

if [ ! -z "$STARTUP_SCRIPT" ]; then
  bash $STARTUP_SCRIPT
fi

echo >&2 "starting php-fpm"

exec /usr/sbin/php-fpm 2>&1
