#!/usr/bin/with-contenv bash
echo >&2 "starting inlets"

export inlets_token=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13)
echo "inlets token is \`${inlets_token}\`"

exec /usr/local/bin/inlets server --port 8000 --control-port 8001 --token "${inlets_token}" 2>&1
